import './js/slick'
import './js/header-scroll'
import './js/modal-table'
import './js/modal-room'
import './js/modal-price'
import './js/anchor-scroll'
import './js/modal-price-2-place'
import './js/modal-price-3-place'
